package tests

import (
	"reflect"
	"testing"

	"github.com/src-d/go-kallax"
	"github.com/stretchr/testify/suite"
)

type QuerySuite struct {
	BaseTestSuite
}

func TestQuerySuite(t *testing.T) {
	schema := []string{
		`CREATE TABLE query (
			id uuid primary key,
			foo varchar(10)
		)`,
	}
	suite.Run(t, &QuerySuite{BaseTestSuite{initQueries: schema}})
}

func (s *QuerySuite) TestQuery() {
	store := NewQueryFixtureStore(s.db)
	doc := NewQueryFixture("bar")
	s.Nil(store.Insert(doc))

	query := NewQueryFixtureQuery()
	query.Where(kallax.Eq(Schema.QueryFixture.ID, doc.ID))

	s.NotPanics(func() {
		s.Equal("bar", store.MustFindOne(query).Foo)
	})

	notID := kallax.NewID()
	queryErr := NewQueryFixtureQuery()
	queryErr.Where(kallax.Eq(Schema.QueryFixture.ID, notID))
	s.Panics(func() {
		s.Equal("bar", store.MustFindOne(queryErr).Foo)
	})
}

// TODO: https://github.com/src-d/go-kallax/issues/39
// this testcase can be removed once the .FindByID
// has been autogenerated
func (s *QuerySuite) TestExistFindByIdMethod() {
	query := NewQueryFixtureQuery()
	queryValue := reflect.ValueOf(query)
	method := reflect.Indirect(queryValue).MethodByName("FindById")
	s.True(method.IsValid(), "TODO: https://github.com/src-d/go-kallax/issues/39")
}

// TODO: https://github.com/src-d/go-kallax/issues/39
// this testcase should be enabled once the .FindByID
// has been autogenerated
/*
func (s *QuerySuite) TestFindById() {
	store := NewQueryFixtureStore(s.db)

	doc := NewQueryFixture("baz")
	s.Nil(store.Insert(doc))

	query := NewQueryFixtureQuery()

	query.FindById(doc.ID)
	s.NotPanics(func() {
		s.Equal("bar", store.MustFindOne(query).Foo)
	})

	notID := kallax.NewID()
	queryErr := NewQueryFixtureQuery()
	queryErr.FindById(notID)
	s.Panics(func() {
		s.Equal("bar", store.MustFindOne(queryErr).Foo)
	})
}
*/
